

qt_home =c:/Qt/4.0.0

opengl_lib = -lopengl32
qt_inc = -I$(qt_home)/include -I$(qt_home)/include/QtGui -I$(qt_home)/include/QtCore -I$(qt_home)/include/QtOpenGL
qt_lib = -L$(qt_home)/lib -L$(qt_home)/bin -lQtCore4 -lQtGui4 -lqtmain -lQtOpenGL4


freetype_inc = -Ic:/freetype/include -Ic:/freetype/include/freetype2
freetype_lib = -Lc:/freetype/lib -Lc:/zlib -lfreetype.dll -lz  



	
all: gui fdtd src/autogenerated/moc.cpp src/aisne.cpp 
	g++ src/aisne.cpp fdtd.o fdtd3d.o source.o panel.o panel3d.o font.o \
	-o aisne.exe -fpermissive -lm $(qt_inc) $(freetype_inc) \
	$(qt_lib) $(freetype_lib) $(opengl_lib)	

fdtd: src/fdtd.cpp src/fdtd3d.cpp src/source.cpp
	g++ -c src/fdtd.cpp -o fdtd.o $(qt_inc)
	g++ -c src/fdtd3d.cpp -o fdtd3d.o $(qt_inc)
	g++ -c src/source.cpp -o source.o $(qt_inc)
	
gui: src/GLcomponents/panel.cpp
	g++ -c src/GLcomponents/panel.cpp -o panel.o  $(qt_inc) $(freetype_inc)
	g++ -c src/GLcomponents/panel3d.cpp -o panel3d.o  $(qt_inc) $(freetype_inc)
	g++ -c src/GLcomponents/font.cpp -o font.o  $(qt_inc) $(freetype_inc)

src/autogenerated/moc.cpp: src/aisne.cpp
	moc -o src/autogenerated/moc.cpp $(qt_inc) $(freetype_inc) $< -o $@

	