

qt_home =c:/Qt/4.0.0

opengl_lib = -lopengl32
qt_inc = -I$(qt_home)/include -I$(qt_home)/include/QtGui -I$(qt_home)/include/QtCore -I$(qt_home)/include/QtOpenGL
qt_lib = -L$(qt_home)/lib -L$(qt_home)/bin -lQtCore4 -lQtGui4 -lqtmain -lQtOpenGL4


freetype_inc = -Ic:/freetype/include -Ic:/freetype/include/freetype2
freetype_lib = -Lc:/freetype/lib -Lc:/zlib -lfreetype.dll -lz  


windows_flags = -Wl,-subsystem,windows # prevents command prompt from appearing


	
all: src/autogenerated/moc.cpp
	g++ src/aisne.cpp -o release/aisne.exe -fpermissive -lm $(qt_inc) $(freetype_inc) \
	$(qt_lib) $(freetype_lib) $(opengl_lib)	

src/autogenerated/moc.cpp: src/aisne.cpp
	moc -o src/autogenerated/moc.cpp $(qt_inc) $(freetype_inc) $< -o $@

	